### ISSUE TITLE
Thumbnails lost after upgrading to 5.3.0 (also to 5.2.1)

### ISSUE THREAD

**Issue by Ni-Ti** [YunoHost-Apps/lychee_ynh#112]
### Describe the bug

![image](https://github.com/YunoHost-Apps/lychee_ynh/assets/88101913/21c864d8-7e75-4636-bb67-d944a70c1b04)

![image](https://github.com/YunoHost-Apps/lychee_ynh/assets/88101913/8cac13cf-b32e-420a-9f45-d7151e0658fa)

### Context

- Hardware: Virtual machine
- YunoHost version: 11.2.11.3

### Steps to reproduce

`# yunohost app upgrade lychee`

### Logs

The update is going well.
Maybe these two lines during the update are related to this bug?
```
Warning: -APP_KEY=<key>
Warning: +APP_KEY=
```

**Comment by ericgaspar** [comment]
A fix can be tested here `sudo yunohost app upgrade lychee -u https://github.com/YunoHost-Apps/lychee_ynh/tree/testing`

**Comment by Ni-Ti** [comment]
The testing version does not fix the bug. :confused:

**Comment by ericgaspar** [comment]
fixed with https://github.com/YunoHost-Apps/lychee_ynh/pull/117
