### ISSUE TITLE
Where are the files stored?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/lychee_ynh#20]
I was wondering where are the files stored so I can properly backup this app. Thanks!

**Comment by TROMsite** [comment]
I see in var/www which is not as great for backups. Can it be hosted in home/yunohost.app ?

**Comment by ericgaspar** [comment]
Yes, my plan is to store media in `/home/yunohost.app/lychee`

**Comment by TROMsite** [comment]
Yup that would be really useful! Looking forward to that for sure! Thanks a lot!

**Comment by ericgaspar** [comment]
Actually, the testing branch is already storing media in `/home/yunohost.app/lychee` path. My concerne before pushing to master is how to upgrade without losing anything in the process...

**Comment by TROMsite** [comment]
Ah ok I see. It is fantastic that it already is implemented. As for the update yah...if you need any testing let me know we can do that on our instance since it is for testing purposes for now.
