### ISSUE TITLE
Better default limit size

### ISSUE THREAD

**Issue by HyroVitalyProtago** [YunoHost-Apps/lychee_ynh#39]
I think we just need to uncomment this two lines in the php-fpm conf, because the default php values are too tiny.
https://github.com/YunoHost-Apps/lychee_ynh/blob/3b2351d9fa198be0477ee51b8c7ee147926a3667/conf/php-fpm.conf#L422-L423

**Comment by pinq-** [comment]
did you manage change this setting somehow?

**Comment by ericgaspar** [comment]
changes have been added to the testing branch.

**Comment by pinq-** [comment]
How can I edit my self? I can't find the conf file.

**Comment by pinq-** [comment]
In the mean time, how can I increase filesize limit? Where I can find the settings?

**Comment by tituspijean** [comment]
PHP upload file limit can be manually tweaked in `/etc/php/$PHP_VERSION/pool.d/lychee.conf`. Currently `$PHP_VERSION = 8.0`.

Closing, since eric increased it the aforementioned pull requests.
