### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by michael-patzer** [YunoHost-Apps/lychee_ynh#41]
### Describe the bug

Installation of lychee fails. My Yunohost is a fresh install with Nextcloud, Jellyfin, and Vaultwarden installed first. 

Relevant warnings:
```
WARNING - E: Packages need to be removed but remove is disabled.
....
WARNING - Package php8.0-json is a virtual package provided by:
WARNING -   php8.0-phpdbg 8.0.17-1+0~20220320.31+debian10~1.gbp34e045
WARNING -   php8.0-fpm 8.0.17-1+0~20220320.31+debian10~1.gbp34e045
WARNING -   php8.0-cli 8.0.17-1+0~20220320.31+debian10~1.gbp34e045
WARNING -   php8.0-cgi 8.0.17-1+0~20220320.31+debian10~1.gbp34e045
WARNING -   libphp8.0-embed 8.0.17-1+0~20220320.31+debian10~1.gbp34e045
WARNING -   libapache2-mod-php8.0 8.0.17-1+0~20220320.31+debian10~1.gbp34e045
WARNING - E: Package 'php8.0-json' has no installation candidate
DEBUG - + ynh_die '--message=Unable to install dependencies'
WARNING - Unable to install dependencies
DEBUG - + ynh_exit_properly
ERROR - Unable to install lychee: An error occurred inside the app installation script
```

### Context

- Hardware: HP EliteDesk
- YunoHost version: 4.3.6.3
- I have access to my server through the webadmin.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: 4.4~ynh2

### Steps to reproduce

- Attempt to install `lychee` app from web-admin panel.

### Logs

https://paste.yunohost.org/raw/kikijizoyu

**Comment by michael-patzer** [comment]
These are the two packages the install script is trying to remove, but the warning says remove is disabled. I'm not sure why these need to be removed.
```
2022-04-05 14:05:40,343: DEBUG - The following packages will be REMOVED:
2022-04-05 14:05:40,344: DEBUG -   nextcloud-ynh-deps php-imagick
```

**Comment by Yajo** [comment]
I tried today in demo.yunohost.org and got the same problem: https://paste.yunohost.org/raw/tidegeqego

**Comment by ericgaspar** [comment]
a quick fix as been push to master. To be tested...

**Comment by tituspijean** [comment]
Closing, no news is good news.
