### ISSUE TITLE
New update opens installer webpage

### ISSUE THREAD

**Issue by pinq-** [YunoHost-Apps/lychee_ynh#52]
- Hardware: *VPS bought online 
- YunoHost version: 11.0.10.2 
- I have access to my server: *Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 4.4.0
- Logs: https://paste.yunohost.org/raw/gekebukili

![kuva](https://user-images.githubusercontent.com/10464992/204065069-9f0c64a6-67bf-4294-a7d4-a972a538290c.png)
It says to create new database manually.

**Comment by DavidLep0le** [comment]
Hello same issue here...
On yunohost i purge all the lyche's folders in /home/yunohost.app,  /home/yunohost.bkup, in /var/www/html and so. After re-install i succeed to enter in the lychee only once. 
after i got the same : 400 BadRequestHeaderException Invalid token error

![Capture du 2023-02-16 17-05-57](https://user-images.githubusercontent.com/74555046/219421761-21b7edc7-fa25-41bd-a2ec-cc742d2f82f2.png)

**Comment by ericgaspar** [comment]
should be fixed
