### ISSUE TITLE
No login possible / no access to pictures @ 5.0.2~ynh1

### ISSUE THREAD

**Issue by ademant** [YunoHost-Apps/lychee_ynh#95]
### Describe the bug

Visiting the Lychee instance, no login is possible and stored pictures are not available, as described here:
https://forum.yunohost.org/t/cant-login-into-lychee/27911

### Context

- Hardware: VPS bought online & regular AMD64
- YunoHost version: 11.2.9.1
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- If the error occurs in your browser, explain what you did:
   1. Go to start page

### Expected behavior

Login should be possible...

Log of last update:
https://paste.yunohost.org/raw/bufipeleja

**Comment by ericgaspar** [comment]
fixed with https://github.com/YunoHost-Apps/lychee_ynh/pull/117
