### ISSUE TITLE
lychee 5.1.0~ynh1 does not work on yunohost 11.2.9.1

### ISSUE THREAD

**Issue by ademant** [YunoHost-Apps/lychee_ynh#99]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

After a new installation I was asked for a admin account. Afterwards I get the empty screen without any possibilities. Neither login, nor add album etc.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.9.1
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

1. Install Lychee via yunohost web
2. got to new instance
3. add admin account
4. there you are with no possibilities

### Expected behavior

A usable lychee instance

### Logs

![image](https://github.com/YunoHost-Apps/lychee_ynh/assets/40039199/47de62a9-73d5-4b02-be8e-85d6450481ad)

**Comment by KoRnBoy82** [comment]
I just asked for this problem on Lychee's Github and they says it's not on their side. We'll see if this is updated someday.

**Comment by MadMan247** [comment]
Hello,

I would like to confirm, this IS still an issue on yunohost 11.2.11.2.

login button is not functional.

**Comment by KoRnBoy82** [comment]
Was there some work on this issue? It's still an issue as of today with most recent Yunohost and most recent Lychee versions.

**Comment by pagnotta** [comment]
^^
Hi @ericgaspar @OniriCorpe 

are you aware of this issue? See also https://forum.yunohost.org/t/cant-login-into-lychee/27911

**Comment by ericgaspar** [comment]
#117 should fix the issue. Please, reopen if not

**Comment by KoRnBoy82** [comment]
Problem corrected in #117 thanks a lot!
